version: '3'
services:
  #------------------------------------------------------------------------------
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    #    ports:
    #    - "2181:2181"
    networks:
      bitnet:
        ipv4_address: ${ZOOKEEPER_IP_ADDRESS}

  #------------------------------------------------------------------------------
  kafka1:
    image: wurstmeister/kafka
    container_name: kafka1
    #    ports:
    #    - "9092:9092"
    environment:
      BROKER_ID: 0
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:${ZOOKEEPER_PORT}
      KAFKA_LOG_DIRS: /tmp/kafka-logs
      KAFKA_LISTENERS: PLAINTEXT://${KAFKA1_IP_ADDRESS}:${KAFKA1_PORT}
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
      KAFKA_CREATE_TOPICS: ${TOPIC_MEMPOOL_TX_EVENTS}:1:1
      KAFKA_MESSAGE_MAX_BYTES: 4000000
      KAFKA_LOG_RETENTION_MS: 1
      KAFKA_LOG_RETENTION_BYTES: 1
      KAFKA_LOG_RETENTION_CHECK_INTERVAL_MS: 10000
    #fetch.message.max.bytes
    #replica.fetch.max.bytes
    #max.message.bytes
    #message.max.bytes

    networks:
      bitnet:
        ipv4_address: ${KAFKA1_IP_ADDRESS}
    volumes:
      - kafka_data_volume1:/tmp/kafka-logs
    #      - /var/run/docker.sock:/var/run/docker.sock # Esto no deberia ponerse,
    depends_on:
      - zookeeper

  #------------------------------------------------------------------------------
  configuration_server:
    image: ${REGISTRY_HOST}/configuration_server:latest
    container_name: configuration_server
    #    ports:
    #      - "8888:8888"
    environment:
      server.port: ${CONFIGURATION_SERVER_PORT}
    networks:
      bitnet:
        ipv4_address: ${CONFIGURATION_SERVER_IP_ADDRESS}
    volumes:
      - configuration_server_volume:/tmp

  #------------------------------------------------------------------------------
  admin_server:
    image: ${REGISTRY_HOST}/admin_server:latest
    container_name: admin_server
    #    ports:
    #      - "8888:8888"
    environment:
      server.port: ${ADMIN_SERVER_PORT}
      eureka.client.serviceUrl.defaultZone: http://${SERVICE_DISCOVERY_IP_ADDRESS}:${SERVICE_DISCOVERY_PORT}/eureka/
    networks:
      bitnet:
        ipv4_address: ${ADMIN_SERVER_IP_ADDRESS}
    volumes:
      - admin_server_volume:/tmp

  #------------------------------------------------------------------------------
  service_discovery:
    image: ${REGISTRY_HOST}/service_discovery:latest
    container_name: service_discovery
    #    ports:
    #      - "8761:8761"
    networks:
      bitnet:
        ipv4_address: ${SERVICE_DISCOVERY_IP_ADDRESS}
    volumes:
      - service_discovery_volume:/tmp

  #------------------------------------------------------------------------------
  gateway_service:
    image: ${REGISTRY_HOST}/gateway_service:latest
    container_name: gateway_service
    networks:
      bitnet:
        ipv4_address: ${GATEWAY_SERVICE_IP_ADDRESS}
    restart: always
    #TODO: Maybe needed
    #    depends_on:
    #      - configuration_server
    #      - service_discovery
    #      - bitcoind_adapter1
    #      - tx_mempool1
    volumes:
      - gateway_service_volume:/tmp

#------------------------------------------------------------------------------
volumes:
  kafka_data_volume1:
  configuration_server_volume:
  admin_server_volume:
  service_discovery_volume:
  gateway_service_volume:

#------------------------------------------------------------------------------
networks:
  bitnet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16
#        - gateway: 172.18.0.1
