version: "3"
services:

#------------------------------------------------------------------------------
  tx_mempool_mongo1:
    image: mongo:latest
    container_name: tx_mempool_mongo1
    ##    ports:
    ##      - "27017:27017"
    networks:
      bitnet:
        ipv4_address: ${TX_MEMPOOL_MONGO1_IP_ADDRESS}
    volumes:
      - tx_mempool_mongo_volume1:/data/db

#------------------------------------------------------------------------------
  tx_mempool_detached:
    image: ${REGISTRY_HOST}/tx_mempool:latest
    container_name: tx_mempool_test
#    ports:
#      - "8084:8080"
#      - "8085:8081"
    environment:
       txmempool.detached: true
       spring.profiles.active: "prod"
       JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8000"
       spring.cloud.config.enabled: "true"
       spring.cloud.config.fail-fast: "true"
       spring_cloud_config_uri: http://${CONFIGURATION_SERVER_IP_ADDRESS}:${CONFIGURATION_SERVER_PORT}
       eureka.client.serviceUrl.defaultZone: http://${SERVICE_DISCOVERY_IP_ADDRESS}:${SERVICE_DISCOVERY_PORT}/eureka/
       management.server.port: ${TX_MEMPOOL_TEST_MANAGEMENT_PORT}
       server.port: ${TX_MEMPOOL_TEST_PORT}
       spring.cloud.stream.kafka.binder.zkNodes: ${ZOOKEEPER_IP_ADDRESS}
       spring.cloud.stream.kafka.binder.brokers: ${KAFKA1_IP_ADDRESS}      
       spring.cloud.stream.bindings.txMemPoolEvents.destination: ${TOPIC_MEMPOOL_TX_EVENTS}
       spring.data.mongodb.uri: mongodb://${TX_MEMPOOL_MONGO1_IP_ADDRESS}:${TX_MEMPOOL_MONGO1_PORT}/statistics
    networks:
      bitnet:
       ipv4_address: ${TX_MEMPOOL_TEST_IP_ADDRESSS}
    restart: always
   # depends_on:
      #- configuration_server
     # - service_discovery
    volumes:
      - tx_mempool_test_volume:/tmp

#------------------------------------------------------------------------------
networks:
  bitnet:
    driver: bridge
    ipam:
      config:
        - subnet:  172.18.0.0/16
#        - gateway: 172.18.0.1

#------------------------------------------------------------------------------
volumes:
  tx_mempool_test_volume:
  tx_mempool_mongo_volume1:      
