version: '3'
services:
  #------------------------------------------------------------------------------
  #port host:docker
  tx_mempool3:
    image: ${REGISTRY_HOST}/tx_mempool:latest
    container_name: tx_mempool3_otherDB
    #ports:
    #  - "4445:8080"
    environment:
      spring.profiles.active: "prod"
      JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8000"
      spring.cloud.config.enabled: "true"
      spring.cloud.config.fail-fast: "true"
      spring_cloud_config_uri: http://${CONFIGURATION_SERVER_IP_ADDRESS}:${CONFIGURATION_SERVER_PORT}
      eureka.client.serviceUrl.defaultZone: http://${SERVICE_DISCOVERY_IP_ADDRESS}:${SERVICE_DISCOVERY_PORT}/eureka/
      management.server.port: ${TX_MEMPOOL3_OTHERDB_MANAGEMENT_PORT}
      server.port: ${TX_MEMPOOL3_OTHERDB_PORT}
      spring.cloud.stream.kafka.binder.zkNodes: ${ZOOKEEPER_IP_ADDRESS}
      spring.cloud.stream.kafka.binder.brokers: ${KAFKA1_IP_ADDRESS}
      #spring.cloud.stream.bindings.txMemPoolEvents.destination: ${TOPIC_MEMPOOL_TX_EVENTS}
      spring.cloud.stream.bindings.txMemPoolEvents.group: txMemPool3
      spring.data.mongodb.uri: mongodb://${TX_MEMPOOL_MONGO2_IP_ADDRESS}:${TX_MEMPOOL_MONGO2_PORT}/statistics
    networks:
      bitnet:
        ipv4_address: ${TX_MEMPOOL3_OTHERDB_IP_ADDRESSS}
    restart: always
#    depends_on:
#      - configuration_server
#      - service_discovery
    #TODO: Maybe needed
    #      - bitcoind_adapter1
    volumes:
      - tx_mempool3_volume:/tmp

#------------------------------------------------------------------------------
volumes:
  tx_mempool3_volume:

#------------------------------------------------------------------------------
networks:
  bitnet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16
#        - gateway: 172.18.0.1
